### ISSUE TITLE
add support for CORS headers

### ISSUE THREAD

**Issue by maks** [npm/npm-registry-couchapp#108]
I'm working on a npm client to use in-browser and would like to be able to access registry.npmjs.org from a browser webpage without using a proxy.

**Comment by reg4in** [comment]
Please add CORS headers, that would just make everything easier for me.

**Comment by maxleiko** [comment]
:+1:

**Comment by huafu** [comment]
:+1:

**Comment by deathcap** [comment]
:+1: would be great if CORS could be (re-?)enabled to open up many new possibilities for web-based interaction with the NPM registry without proxy hacks.

For reference, this is only a CouchDB configuration change (no code change), in case anyone wants to enable CORS on their own npm-registry-couchapp instance, something like this works:

```shell
curl -X PUT http://admin:password@localhost:5984/_config/httpd/enable_cors -d '"true"'
curl -X PUT http://admin:password@localhost:5984/_config/cors/origins -d '"*"'
curl -X PUT http://admin:password@localhost:5984/_config/cors/methods -d '"GET, HEAD"'
```

then test that it is enabled with:

```shell
curl -i -H 'Origin: example.com' registry.npmjs.org | grep Access-Control

curl -i -H 'Origin: example.com' localhost:5984 | grep Access-Control
…
Access-Control-Expose-Headers: Cache-Control, Content-Type, Server
Access-Control-Allow-Origin: example.com
```

**Comment by expr** [comment]
:+1:

**Comment by kumavis** [comment]
thanks @deathcap!

**Comment by kumavis** [comment]
Here is a CORS proxy service max runs if anyone needs a temporary workaround http://cors.maxogden.com

**Comment by ekonstantinidis** [comment]
+1 Trying to make a request: `XMLHttpRequest cannot load https://registry.npmjs.org/less. Origin http://192.168.1.68:8080 is not allowed by Access-Control-Allow-Origin.`

**Comment by xixixao** [comment]
+1

**Comment by zahhak** [comment]
:+1:

**Comment by kumavis** [comment]
:+1:

**Comment by LuisHerranz** [comment]
Want this! :+1:

**Comment by alexanderbartels** [comment]
:+1:

**Comment by cbornet** [comment]
:+1:

**Comment by cbornet** [comment]
@isaacs any chance this can be enabled again or is there a security issue preventing this ?

**Comment by zeke** [comment]
Hey @ceejbot, @bcoe, @seldo, @isaacs. Any progress on this? Would really love to migrate people off my proxy app.

**Comment by bcoe** [comment]
We had CORS enabled for a period of time, but it unfortunately raised some security concerns: allowing folks to perform arbitrary puts from the browser, opening us up to potential DDoS attacks, etc. We opted to turn CORS back off due to these concerns.

Since this time, we have gradually moved away from adding any updates to npm-registry-couchapp; the codebase has gradually become deprecated as we've moved to a more distributed architecture.

I've officially added a deprecation notice to the repo:

https://github.com/npm/npm-registry-couchapp/pull/252

And I'd love for folks to instead join the conversation here:

https://github.com/npm/public-api

Let's decide on what a public API for npm should look like.

**Comment by dubzzz** [comment]
What is the latest and updated documentation for the public API of npm?

I looked at https://github.com/npm/public-api which redirects to https://github.com/npm/registry.
In https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md we can read that https://registry.npmjs.org/less should work fine but there is still CORS on it.

**Comment by vadzim** [comment]
For visitors:
You can use unpkg (https://unpkg.com/) instead of https://npmjs.com/
Unpkg is a CDN and sets CORS

**Comment by Jolg42** [comment]
Another workaround would be to use npms https://api.npms.io/v2/package/prisma

**Comment by jasonkuhrt** [comment]
@vadzim I don't see a way to get the npm package metadata from unpkg?

@Jolg42 that doesn't offer the npm package metadata either?

**Comment by Jolg42** [comment]
@jasonkuhrt npms offers the same with some differences but mostly the same with extra fields. Though npms had issues in the past with stale data.

**Comment by Jolg42** [comment]
The discussion continues here since this issue is closed and not monitored I guess.

https://github.com/npm/feedback/discussions/117

**Comment by jasonkuhrt** [comment]
This works for us for now https://npmjs.cf/
