### ISSUE TITLE
jsonp is not working for registry.npmjs.org

### ISSUE THREAD

**Issue by anvaka** [npm/npm-registry-couchapp#157]
Hello,

I'm trying to use npm from a browser. 

This returns valid jsonp response:
[http://isaacs.iriscouch.com/registry/_design/scratch/_view/byField?**callback=foo**&limit=10](http://isaacs.iriscouch.com/registry/_design/scratch/_view/byField?callback=foo&limit=10)

However `isaacs.iriscouch.com` was not stable recently, and I'm trying to change endpoint to `registry.npmjs.org`:

http://registry.npmjs.org/-/_view/byField?callback=foo&limit=10

This returns data, but completely ignores callback argument (which makes it unusable for jsonp scenario).

Neither does skimdb respects it:

https://skimdb.npmjs.com/registry/_design/scratch/_view/byField?callback=foo&limit=10

Would really appreciate your help.

Cheers,
Andrei

**Comment by smikes** [comment]
I believe @maxogden said that there is a dat stream for `npm` registry -- see <https://github.com/maxogden/dat>

**Comment by maxogden** [comment]
oh yea we have http://npm.dathub.org/, it's experimental though so don't build anything production off of it

**Comment by anvaka** [comment]
@maxogden I was hoping to use CORS or JSONP enabled endpoint to render dependencies graph here: https://github.com/anvaka/npmgraph.an 

http://npm.dathub.org/api/rows?limit=10 - looks promising, thought it seems CORS/JSONP are not available here either?

**Comment by maxogden** [comment]
It supports CORS GET, but not JSONP

**Comment by vadzim** [comment]
For visitors:
You can use unpkg (https://unpkg.com/) instead of https://npmjs.com/
Unpkg is a CDN and sets CORS
