### ISSUE TITLE
Getting a lot of (new TypeError("doc['dist-tags'] is undefined"

### ISSUE THREAD

**Issue by gregoranders** [npm/npm-registry-couchapp#232]
After following the instructions to replicate the npm registry i am getting a lot of:

[Thu, 16 Apr 2015 09:19:36 GMT] [info] [<0.289.0>] OS Process #Port<0.3301> Log :: function raised exception (new TypeError("doc['dist-tags'] is undefined", "undefined", 2)) with doc._id pex-init
[Thu, 16 Apr 2015 09:19:36 GMT] [info] [<0.289.0>] OS Process #Port<0.3301> Log :: function raised exception (new TypeError("s.split is not a function", "undefined", 4)) with doc._id generator-predix

when indexing is running. I wonder if that is something to worry about and if so... what to do to get rid of these log entries (fixing it).

(Couch 1.6.1, Erlang R16B03 (erts-5.10.4))

**Comment by techird** [comment]
Got the same issue

**Comment by techird** [comment]
Any response here? Need help.
