### ISSUE TITLE
Finding npm-registry-couchapp in a complex node_modules tree

### ISSUE THREAD

**Issue by bengl** [npm/npm-registry-couchapp#243]
Thoughts on adding an `index.js` just exporting the `__dirname` so the code can be found with `require` or `require.resolve`? Admittedly this is probably a bit of a fringe need.

Happy to PR if this is acceptable.

**Comment by aredridel** [comment]
Ever considered substack's resolve package to find it?

**Comment by aredridel** [comment]
(also, a hack: search for its package.json -- `path.dirname(require.resolve('npm-registry-couchapp/package.json'))`

**Comment by bengl** [comment]
2 great answers! Closing.
