### ISSUE TITLE
Feature request: Download stats for npm modules

### ISSUE THREAD

**Issue by christkv** [npm/npm-registry-couchapp#35]
Hi Isaac

This would be great to have but it's not a must.

Cheers

Christian

**Comment by jsdevel** [comment]
@tbergeron  https://github.com/npm/npm-registry-couchapp/issues/35#issuecomment-7158300, I created a [google chrome extension](https://chrome.google.com/webstore/detail/my-npm-downloads/mgjgilnaemgnmggoikpmbeljjmlkpcdp?hl=en) that allows you to quickly see your npm stats on a daily basis.

![my-npm-downloads chrome extension](https://raw.githubusercontent.com/jsdevel/my-npm-downloads/master/screenshot.png)

**Comment by bencevans** [comment]
Nice! I've found http://npm-stat.com/charts.html to be pretty decent when
you want a quick look at the stats too.

**Comment by salqadri** [comment]
Can the same client be the source of multiple downloads? If so, is there a way we can see stats on just the unique npm installs?
