### ISSUE TITLE
Allow groups via roles.

### ISSUE THREAD

**Issue by bmeck** [npm/npm-registry-couchapp#93]
the maintainer's field should allow for grouping of some kind and check validate_doc_update against the userContext.roles, in particular a schema of "group/$NAME" would be fine for roles. Don't know if this needs much more, but since we are working with _users as a flat namespace we need to prefix the groups to distinguish them in the maintainers field somehow.

**Comment by bcoe** [comment]
I've officially added a deprecation notice to the repo:

#252

And I'd love for folks to instead join the conversation here:

https://github.com/npm/public-api

Let's decide on what a public API for npm should look like.
